Add CI/CD for Docker Build and Sonar cloud
usdot-jpo-ode/jpo-security-svcs pull request #18
Opened 2023-04-10 18:53 UTC by SaikrishnaBairamoni

This PR is to add the GitHub actions workflows for both docker hub build and to run sonar scan analysis for publishing static reports on sonar cloud dashboard.

2023-04-10 20:04 UTC, codygarver requested changes
sonar-scanner.properties is not being used by the sonar-scanner in ci.yml

ci.yml is also needs to include [tmca-tester](https://github.com/usdot-jpo-ode/jpo-security-svcs/tree/develop/tmca-tester)

2023-06-20 15:00 UTC, codygarver requested changes
See diff comments

2023-06-20 15:00 UTC, codygarver commented on .github/workflows/ci.yml
> +         npm i
`npm i` is unnecessary since the next line does npm install

2023-06-20 15:00 UTC, codygarver commented on .github/workflows/ci.yml
> +      - run: chmod +x -R /home/runner/work/jpo-security-svcs/jpo-security-svcs
Does the build work without this?

2023-06-20 15:00 UTC, codygarver commented on .github/workflows/docker.yml
> +      - "release/*"
Do we want `master` in this list?

2023-06-20 15:00 UTC, codygarver commented on .github/workflows/docker.yml
> +          file: ./Dockerfile
I think these lines are unnecessary and can be removed

2023-06-20 15:00 UTC, codygarver commented on .github/workflows/dockerhub.yml
> +      - "develop"
Do we want to also include `master` and `release/*`

2023-06-20 15:00 UTC, codygarver commented on .github/workflows/dockerhub.yml
> +  dockerhub-Jpo-ode:
lowercase this `J`

2023-06-20 15:00 UTC, codygarver commented on .sonarqube/sonar-scanner.properties
> +#jpo-security-svcs.sonar.tests                = src/test
Delete this whole file, it doesn't get used anywhere

2023-06-20 15:00 UTC, codygarver commented on pom.xml
> +        <sonar.language>java</sonar.language>
Replace tabs with spaces and properly indent within `<properties>`

2023-06-20 15:00 UTC, codygarver commented on pom.xml
> +          <artifactId>maven-surefire-plugin</artifactId>
When does anything with `surefire` get used?

2023-06-20 15:00 UTC, codygarver commented on pom.xml
> +              <groupId>org.apache.maven.surefire</groupId>
When does anything with `surefire` get used?

2023-06-20 23:18 UTC, SaikrishnaBairamoni commented on .github/workflows/ci.yml
> +         npm i
removed

2023-06-20 23:18 UTC, SaikrishnaBairamoni commented on .github/workflows/docker.yml
> +      - "release/*"
updated

2023-06-20 23:18 UTC, SaikrishnaBairamoni commented on .github/workflows/dockerhub.yml
> +      - "develop"
updated

2023-06-20 23:18 UTC, SaikrishnaBairamoni commented on .sonarqube/sonar-scanner.properties
> +#jpo-security-svcs.sonar.tests                = src/test
deleted

2023-06-21 00:43 UTC, codygarver requested changes

2023-06-21 00:43 UTC, codygarver commented on .github/workflows/docker.yml
> +      - run: ls -la && pwd
Remove this `run:` line

2023-06-21 00:43 UTC, codygarver commented on pom.xml
> +          <!-- JaCoCo Properties -->
Fix this alignment, too many spaces

2023-06-21 13:49 UTC, codygarver requested changes
See diff in comments

2023-06-21 13:49 UTC, codygarver commented on .github/workflows/ci.yml
> +         npm install node-menu@1.3.2
Remove this line about node-menu, no need to manually install a dependency already declared in package.json

2023-06-21 13:49 UTC, codygarver commented on .github/workflows/ci.yml
> +     - name: build tmca-tester
tmca-tester should be a dedicated job so it can run in parallel

2023-06-21 13:49 UTC, codygarver commented on .github/workflows/ci.yml
> +    needs: [jpo-security-svcs]
Add tmca-tester job as a dependency when you split it to its own job

2023-06-28 20:00 UTC, codygarver requested changes

2023-06-28 20:00 UTC, codygarver commented on .github/workflows/ci.yml
> +         npm run build --if-present
Why `--if-present`?

2023-06-28 20:03 UTC, SaikrishnaBairamoni commented on .github/workflows/ci.yml
> +         npm run build --if-present
removed

2023-06-28 20:27 UTC, codygarver approved these changes

2023-06-28 20:27 UTC, merged